### ISSUE TITLE
Yahoo iCharts no longer in service

### ISSUE THREAD

**Issue by srowen** [sryza/aas#109]
Oh dear, looks like iCharts (used in Ch 9) was discontinued this month. Just in time for the 2nd edition to be in print with references to it. https://forums.yahoo.net/t5/Yahoo-Finance-help/Is-Yahoo-Finance-API-broken/m-p/250503#U250503

There's probably a way to rejigger the scripts to download from something like http://www.google.com/finance/historical?q=AAPL&startdate=Jan+01%2C+2000&output=csv without much change to the subsequent parsing, but it won't be exactly the same.

**Comment by tedtang77** [comment]
Yes, I encounter the same issue...

**Comment by feelmercy** [comment]
Hi Sean ,
Is there other way or place to download the csv files?

**Comment by sryza** [comment]
Yikes. I'll try to take a look at this over the weekend.

**Comment by feelmercy** [comment]
You can  use this (replace download-symbol.sh ) to download data
wget -O  ${2}/${1}.csv "http://www.google.com/finance/historical?q=${1}&startdate=
Jan+01%2C+2000&enddate=Dec+31%2C+2013&output=csv"
