### ISSUE TITLE
Error: type mismatch trips.GroupedIterator[Trip]  (ch08-geotime/RunGeoTime.scala)

### ISSUE THREAD

**Issue by tedtang77** [sryza/aas#110]
When executing below codes in spark-shell following the instructions in the book, I get below error. Please can someone let me know how to solve it?
(note: spark 2.1.0)

( aas/ch08-geotime/src/main/scala/com/cloudera/datascience/geotime/RunGeoTime.scala )
val boroughDurations: DataFrame =
  | sessions.mapPartitions(trips => {
  | val iter: Iterator[Seq[Trip]] = trips.sliding(2)
  | val viter = iter.filter(_.size == 2).filter(p => p(0).license == p(1).license)
  | viter.map(p => boroughDuration(p(0), p(1)))
  | }).toDF("borough", "seconds")

--------------------error message----------------------------------
<console>:106: error: type mismatch;
 found   : trips.GroupedIterator[Trip(in class $iw)]
 required: Iterator[Seq[Trip(in class $iw)]]
               val iter: Iterator[Seq[Trip]] = trips.sliding(2)
                                                                              ^

**Comment by srowen** [comment]
Long overdue, but: 
Hm, this compiles and runs in the CI builds now. It could be an artifact of running it in the shell. Try pasting all of the code together in one big block with `:paste`. I've seen odd problems with types when pasting things one at a time as the shell puts code in its own package. 
Else, check you're running the code as found in the repo, that's the latest, and make sure you're not using a different version of the geo library.
