### ISSUE TITLE
[ch06-lsa] can not import edu.umd._ and edu.stanford._ in all-spark-notebook

### ISSUE THREAD

**Issue by jhhan45** [sryza/aas#114]
Hello,
I have studied the Spark machine learning through Advanced Analytics with Spark, 2nd edition. 
To practice the example code, I have used docker and jupyter notebook (https://hub.docker.com/r/jupyter/all-spark-notebook/).
Until chapter 5, all practice codes are working well.

In chapter 6, we need some external dependencies, so I followed the instructions. 
Clone the git repository and successfully compile the jar file using maven. 
But I'm using the jupyter notebook, so I can't start the spark-shell in command line, like `spark-shell --jars XXX.`
I start the Spark shell in jupyter notebook, using Apache Toree-Scala.
So, I add the external jar dependencies in the code.

`sc.addJar("aas/ch06-lsa/target/ch06-lsa-2.0.0-jar-with-dependencies.jar")`
`import edu.umd.cloud9.collection.XMLInputFormat`

But I got this error message.
```
Name: Compile Error
Message: <console>:88: error: object umd is not a member of package edu
       import edu.umd.cloud9.collection.XMLInputFormat
                  ^
StackTrace: 
```
The jar file path is correct and the `addJar` method did not occur any errors.

Anyone can help to solve this problem???

Thanks!

**Comment by srowen** [comment]
The problem is that you're adding the class to Spark's config, but not telling Toree about it. You need to use something like its `%AddJar` magic to make it work in the shell.

**Comment by jhhan45** [comment]
Thanks for your reply. 
So I add the `%AddJar` magic and it works fine. 
The `/tmp/toree_add_jarXXX` is created and the jar file is saved.
But still I have the same error message. 

```
%AddJar --magic -f file:/home/jovyan/aas/ch06-lsa/target/ch06-lsa-2.0.0-jar-with-dependencies.jar
res: Starting download from file:/home/jovyan/aas/ch06-lsa/target/ch06-lsa-2.0.0-jar-with-dependencies.jar
res: Finished download of ch06-lsa-2.0.0-jar-with-dependencies.jar

```
```
import edu.umd.cloud9.collection.XMLInputFormat
Name: Compile Error
Message: <console>:17: error: object umd is not a member of package edu
       import edu.umd.cloud9.collection.XMLInputFormat
                  ^
StackTrace: 
```

I don't know why... 
Do you have any other ideas to solve this error?

**Comment by jhhan45** [comment]
Yay~! I solve the problem. 
I should remove `--magic` option from `%Addjar` magic.
Thanks for your help~~
