### ISSUE TITLE
[ch-08] At the jupyter notebook Apache Toree - Scala shell, the class RichGeometry is not defined

### ISSUE THREAD

**Issue by jhhan45** [sryza/aas#117]
I used the Spark at the jupyter notebook Apache Toree Scala shell.

I tried to follow the code in ch08 and I successfully compile the external dependencies and import them. 

But when I try to define `class RichGeometry` , the Spark shell made errors as follows

`Name: Compile Error
Message: <console>:13: error: not found: type Geometry
       class RichGeometry(val geometry: Geometry,
                                        ^
<console>:14: error: not found: type SpatialReference
       val spatialReference: SpatialReference =
                             ^
<console>:15: error: not found: value SpatialReference
       SpatialReference.create(4326)) {
       ^
<console>:17: error: not found: type Geometry
       def contains(other: Geometry): Boolean = {
                           ^
<console>:18: error: not found: value GeometryEngine
       GeometryEngine.contains(geometry, other, spatialReference)
       ^
<console>:20: error: not found: type Geometry
       def distance(other: Geometry): Double = {
                           ^
<console>:21: error: not found: value GeometryEngine
       GeometryEngine.distance(geometry, other, spatialReference)
       ^`

I successfully import dependencies as follows:

`import com.esri.core.geometry.Geometry
import com.esri.core.geometry.GeometryEngine
import com.esri.core.geometry.SpatialReference`

So I don't know why it said that type Geometry, type SpatialReference are not found.

Thanks~~

**Comment by srowen** [comment]
That sounds more like a Toree issue. If it's imported but not found at all, I don't think it can be related to the book code.
