### ISSUE TITLE
transform RDD [(String, String)] to DATASET [ (String, String)]

### ISSUE THREAD

**Issue by jonnathanjuma** [sryza/aas#127]
I'm new to scala and I'm trying to read documents from a folder but I can only load them as val rdd: RDD [(String, String)] = spark.sparkContext .wholeTextFiles ("/ user / ds /") and not how to transform it to DATASET [ (String, String)] to use it in ch06-lsa

**Comment by srowen** [comment]
Just call `.toDS` on the RDD
