### ISSUE TITLE
Ch 03: audioscrobbler data not available

### ISSUE THREAD

**Issue by arash2060** [sryza/aas#131]
This link is broken and I cannot find the data set anywhere else: http://www-etud.iro.umontreal.ca/~bergstrj/audioscrobbler_data.html

Could you provide it?

**Comment by arash2060** [comment]
It seems that the data is available from http://www.iro.umontreal.ca/~lisa/datasets/profiledata_06-May-2005.tar.gz

**Comment by srowen** [comment]
Thanks, yes, it was removed a while ago. We can't update the book but the github README here already has an alternative link to it.
