### ISSUE TITLE
how to work around "next on empty iterator"in chapter 9th?

### ISSUE THREAD

**Issue by appleyuchi** [sryza/aas#133]
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/05/16 15:33:51 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
19/05/16 15:33:51 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeRefBLAS
Exception in thread "main" java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
	at scala.collection.IterableLike$class.head(IterableLike.scala:107)
	at scala.collection.mutable.ArrayOps$ofDouble.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:270)
	at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:126)
	at scala.collection.mutable.ArrayOps$ofDouble.head(ArrayOps.scala:270)
	at RunRisk.fivePercentVaR(RunRisk.scala:274)
	at RunRisk$.main(RunRisk.scala:49)
	at RunRisk.main(RunRisk.scala)

the code I use is:
https://paste.ubuntu.com/p/tCjkHjwgmC/
any help or advice  is appreciated,
thanks in advance~

**Comment by srowen** [comment]
I think you are not successfully reading the input. This indicates you don't end up producing trials to analyze. If you've modified the code, I think it's somewhere in your modification.

**Comment by appleyuchi** [comment]
but I only modify 3 point:
class RunRisk(private val spark: SparkSession) extends java.io.Serializable 
modify    path
modify     val formatter = DateTimeFormatter.ofPattern("d-MMM-yy",Locale.ENGLISH)
@srowen 
could you help me?thanks ~~~

um....my environment is:
ubuntu18.10
spark2.3.1

**Comment by appleyuchi** [comment]
if I did NOT modify the above three point ,there will be error log....

**Comment by appleyuchi** [comment]
I use trials.show(),the content is:
+-----+
|value|
+-----+
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
|  NaN|
+-----+

**Comment by appleyuchi** [comment]
I found 

    for (i <- 0 until numTrials) {
      val trialFactorReturns = multivariateNormal.sample()
      val trialFeatures = featurize(trialFactorReturns)
      trialReturns(i) = trialReturn(trialFeatures, instruments)

    }

this code make trialReturns(i) from 0 ->NaN

**Comment by appleyuchi** [comment]
I traced back and found totalReturn is NaN

**Comment by appleyuchi** [comment]
when CVCY.csv is in folder stocks/ then totalreturns will be NaN
is it Right?

**Comment by appleyuchi** [comment]
The return value of readGoogleHistory is **Array[(LocalDate, Double)**
while the type of allStocks is **Iterator[Array[(LocalDate, Double)]]**(auto inference by intellij with scala 2.11.8)
here it seems not works well.

Could you give me more tips?
@srowen 
much thanks~

**Comment by srowen** [comment]
The code compiles and runs fine. I'm not even clear what you're saying the problem is; `allStocks` is an iterator over results of `readGoogleHistory`.
I think you don't have the data downloaded. You need to download or unzip it from the .zip file provided. This code doesn't work out of the box any more because the original data moved, so there are extra steps here.

**Comment by appleyuchi** [comment]
**stocksReturns.map(linearModel(_, factorFeatures)).map(_.estimateRegressionParameters()).toArray**

I found this code returns a lot of NaN
stocksReturns is not null
factorFeatures is not null


do you know how to modify it?
thanks~
@srowen

**Comment by appleyuchi** [comment]
I check the doument of  [estimateRegressionParameters()](http://commons.apache.org/proper/commons-math/javadocs/api-3.5/org/apache/commons/math3/stat/regression/OLSMultipleLinearRegression.html)


it said:
If there is no variance in y, i.e., SSTO = 0, NaN is returned.

in my **stocksReturns** and **factorFeatures**,there's so much 0 s,which may be the reason why ch09-code fails in my platform.
