### ISSUE TITLE
mvn package getting failed for chapter 6 lsa

### ISSUE THREAD

**Issue by svishnu88** [sryza/aas#14]
Hi ,

I am trying to practice chapter 6. I am trying to build the package as mentioned in the book  but i am stuck with the below error.

[ERROR] Failed to execute goal on project ch06-lsa: Could not resolve dependencies for project com.cloudera.datascience:ch06-lsa:jar:1.0.0: Failure to find com.cloudera.datascience:common:jar:1.0.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 

Thanks,
Vishnu

**Comment by srowen** [comment]
Are you trying to compile just `ch06-lsa`? Really you'll have to do one of two things:

- Run `mvn package` from the root to compile and package everything
- Run `mvn install` or at least `mvn install -pl common` from the root to make the `common` artifact available, then `mvn package` from inside `ch06-lsa`

I recommend the former. I can update the docs to make this clear, if that's the solution.

**Comment by svishnu88** [comment]
Thanks srowen. It worked after following the above steps.

**Comment by jackRogers** [comment]
After following this instructions, I get an error when trying to load in XmlInputFormat

scala> import com.cloudera.datascience.common.XmlInputFormat
<console>:19: error: object common is not a member of package com.cloudera.datascience
       import com.cloudera.datascience.common.XmlInputFormat

**Comment by jackRogers** [comment]
resolved using 
spark-shell --jars target/ch06-lsa-1.0.0-jar-with-dependencies.jar

**Comment by srowen** [comment]
Yep, good point, in that case it's not sufficient to just copy and paste code in the shell. You'll want to probably add the compiled code to the classpath in order to get access to `XmlInputFormat`

**Comment by mongoose54** [comment]
@srowen How can I include "com.cloudera.datascience:common:jar:1.0.0 " into my build.sbt of my SBT project ? Right now I have the following:

```
name := "app"

version := "1.0"

scalaVersion := "2.10.4"

libraryDependencies ++= Seq(
  "org.apache.spark"  %% "spark-graphx" % "1.4.0"  % "provided",
  "org.apache.spark"  %% "spark-mllib"  % "1.4.0"  % "provided" ,
  ("org.apache.spark" %% "spark-core" % "1.4.0" % "provided").
    exclude("org.mortbay.jetty", "servlet-api").
    exclude("commons-beanutils", "commons-beanutils-core").
    exclude("commons-collections", "commons-collections").
    exclude("commons-logging", "commons-logging").
    exclude("com.esotericsoftware.minlog", "minlog"),
  "org.apache.hadoop" % "hadoop-client" % "2.7.1",
  "com.cloudera.datascience"  %% "common" % "1.0.0"
)
```

But I get an "unresolved dependency" error on com.cloudera.datascience#common

**Comment by srowen** [comment]
The code is not published to Maven; I don't think it's intended to be reused as if a library in another app. However you can pretty easily `mvn install` all of the artifacts in your local repository and build an SBT project that can see the Maven artifacts in `.m2/repository`, I suppose.
