### ISSUE TITLE
Reproducible exercise

### ISSUE THREAD

**Issue by woblak** [sryza/aas#140]
This is not reproducible. Where is the dataset?
In book I have found that we can download it from https://bit.ly/1KiJdOR
but the files are not able to download now.

**Comment by laserson** [comment]
Hi @woblak, could you give more details about what specific problem you are having?

**Comment by woblak** [comment]
I want to get data set used in this code: https://github.com/sryza/aas/blob/master/ch03-recommender/src/main/scala/com/cloudera/datascience/recommender/RunRecommender.scala

for example "user_artist_data.txt"

In the book "Advance Analytics with Spark" there is written then we can download it from https://bit.ly/1KiJdOR but the side is not avaidable now.

**Comment by srowen** [comment]
Please see https://github.com/sryza/aas for the latest location of the data. We can't update the paper books of course retroactively, so maintain the links here.
