### ISSUE TITLE
Chapter 3. Recommending Music and the Audioscrobbler Dataset

### ISSUE THREAD

**Issue by tanthiamhuat** [sryza/aas#149]
I do not see "test" and "train" being defined.
So how can the below code works?

`from pyspark.ml.recommendation import ALS

als = ALS(maxIter=5, regParam=0.01, userCol="user", itemCol="artist", ratingCol="count")

model = als.fit(train)

predictions = model.transform(test)`

**Comment by analyticalmonk** [comment]
Hi @tanthiamhuat, this one's a non-functional code snippet as is mentioned in the line preceding this block. 
![Screenshot from 2022-07-05 14-34-49](https://user-images.githubusercontent.com/4419448/177292446-8cdc80e9-7dd9-4297-a8ab-22d32c6ee848.png)


That is, it is only provided as an example of the syntax and is not meant to be run.

**Comment by tanthiamhuat** [comment]
oh, I see, thanks for clarification.
