### ISSUE TITLE
Chapter 3: Convert PySpark DataFrame to Pandas

### ISSUE THREAD

**Issue by tanthiamhuat** [sryza/aas#150]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/9988941/177336282-6379aa74-f229-4423-99cc-dc1f2a2ff1f6.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/9988941/177336429-02c91c18-aceb-49bc-8c02-84ad8171dd71.png">

Is it because recommendations is of type array, it creates some issue when need to convert to Pandas?
How do we overcome this?

**Comment by srowen** [comment]
This is fine, it's a warning that arrow optimizations do not apply to this case, but that's normal.

**Comment by tanthiamhuat** [comment]
yup, it is a warning.. but I am not sure why I am not allowed to print it out, as that variable 'top_prediction_pandas' is not defined. However, its below code with the variable 'top_prediction_pandas' runs fine.
![image](https://user-images.githubusercontent.com/9988941/177453950-153afebc-6fc9-4216-9ffe-f2be1d5966ae.png)

**Comment by srowen** [comment]
There is a typo here - top_prediction_pandas vs top_predictions_pandas

**Comment by tanthiamhuat** [comment]
oic, thank you, we can close this issue.
