### ISSUE TITLE
Chapter 3: ROC

### ISSUE THREAD

**Issue by tanthiamhuat** [sryza/aas#151]
sorry for the many questions, because I could not get through the code. How do you get ROC about 0.879? What are the details inside the function area_under_curve?
I suppose we need to have the data for:
cv_data, b_all_artist_ids, model.transform to be input for the area_under_curve function.
But even that, I had error for b_all_artist_ids
<img width="788" alt="image" src="https://user-images.githubusercontent.com/9988941/177341848-66ca6b4c-4a05-43a7-a2fa-7543f69a8cb1.png">

**Comment by srowen** [comment]
@analyticalmonk will have to supply the full code listings.
That line looks like a bug in the listing unfortunately - it can't be broadcasting an int. I assume the `.count()` should be removed on the line before.

**Comment by tanthiamhuat** [comment]
but it looks to me that the function 'area_under_curve' needs to be defined too, else how can it be used?

**Comment by srowen** [comment]
Yes, that's what I said?

**Comment by analyticalmonk** [comment]
@tanthiamhuat the `area_under_curve` code is available in the chapter 3 notebook on the [pyspark branch](https://github.com/sryza/aas/tree/pyspark-edition).
