### ISSUE TITLE
maven build errors for XmlInputFormat.java involving StandardCharsets

### ISSUE THREAD

**Issue by d3borah** [sryza/aas#18]
Maven build errors  for XmlInputFormat.java. Stacktrace indicates maven plugin issue (MojoExecutor)

errors like this
".../common/XmlInputFormat.java:[21,24] cannot find symbol
symbol : class StandardCharsets
location: package java.nio.charset "

I'm on java 7. 
java version "1.7.0_71"

rolling back to previous version of XmlInputFormat.java (including Guava) works. 

Thanks for any guidance.

**Comment by srowen** [comment]
You need to build this code with Java 7
