### ISSUE TITLE
Chapter 10 build broken by an ADAM change

### ISSUE THREAD

**Issue by tomfaulhaber** [sryza/aas#19]
I just pulled the book source (master 94fa09d) and got the following error when running mvn:

```
[INFO] --- scala-maven-plugin:3.2.0:compile (default) @ ch10-genomics ---
[INFO] artifact joda-time:joda-time: checking for updates from central
[INFO] /Users/tom/src/scala/aas/ch10-genomics/src/main/scala:-1: info: compiling
[INFO] Compiling 1 source files to /Users/tom/src/scala/aas/ch10-genomics/target/classes at 1424131711406
[ERROR] /Users/tom/src/scala/aas/ch10-genomics/src/main/scala/com/cloudera/datascience/genomics/RunTFPrediction.scala:16: error: object FeaturesContext is not a member of package org.bdgenomics.adam.rdd.features
[ERROR] import org.bdgenomics.adam.rdd.features.FeaturesContext._
[ERROR]                                         ^
```

followed by 8 others in the same file.

This would appear to be caused by the last commit to ADAM (https://github.com/bigdatagenomics/adam/commit/3f0eadbc746511f5f8d07f46d97f2fa920f3f41e) which removed the `FeaturesContext` and `GeneContext` classes and apparently replaced their functions with the more generic `loadFeatures` function in the ADAMContext.

**Comment by srowen** [comment]
Heh, yeah that's happened a number of times as the snapshot changes. Eventually we can depend on the 0.15.1 release when it's out. Uri can patch it up when he has a moment

**Comment by tomfaulhaber** [comment]
Figured it was something like that. Not an urgent problem for me - I'm only to chapter 4 :).

Changing the root pom.xml so that:

```
    <module>ch10-genomics</module> 
```

is commented out:

```
    <!-- <module>ch10-genomics</module> -->
```

drops that chapter and lets everything else build in the meantime (in case anyone else is dealing with this before Uri gets to it).

**Comment by laserson** [comment]
Thanks for reporting this, @tomfaulhaber!
