### ISSUE TITLE
Could cause NumberFormatException not "cause a NumberFormatException"

### ISSUE THREAD

**Issue by dvohra** [sryza/aas#24]
Ch 3 has a statement: "These lines cause a NumberFormatException". The lines don't cause a NumberFormatException but could throw or cause a NumberFormatException.

**Comment by srowen** [comment]
This doesn't make sense. You have said the same thing.

**Comment by dvohra** [comment]
Not the same. The lines of code by themselves don't cause or throw an exception, but could cause or throw an exception if the parsed data has a number format issue. 

In the exception handling definition  you would find "a Method Can Throw an Exception", which is not the same as a method throws an exception. 

https://www.safaribooksonline.com/library/view/scala-cookbook/9781449340292/ch05s09.html

"For each checked exception which is a possible result, the throws clause for the method or constructor must mention the class of that exception"  

The "possible result" is not the same as a method actually throwing or causing an exception.

http://www.scala-lang.org/old/node/106

Also, on testing the lines of code indicated to cause an exception no NumberFormatException is caused, which is to be expected. An NumberFormatException would be caused only if the parsed data has a number format issue.

**Comment by srowen** [comment]
I think you're splitting hairs over wording. We certainly understand how exceptions work. The point is that this line of code does throw an exception if the input is invalid.

**Comment by dvohra** [comment]
It is not just the statement indicated. The paragraph indicates the data has some formatting issue and the NumberFormatException is caused. 

What you may have implied is that if the data has some formatting issue the NumberFormatting issue is caused. 

Just refer to the following paragraph from ch 3:

"A small number of the lines appear to be corrupted. They don’t contain a tab, or, inadvertently include a newline character. These lines cause a NumberFormatException". 

What you probably want to indicate is the following:

"If a small number of the lines appear to
be corrupted or they don’t contain a tab, or, inadvertently include a newline character.
these lines cause a NumberFormatException"

As such the sample data for ch 3 does not cause the NumberFormatException. You may want to modify the paragraph (only a suggestion ) as the paragraph conveys that the NumberFormatExcption would be generated with the sample data.

**Comment by dvohra** [comment]
Also refer to the following paragraph:

However, a straightforward parsing of the file into
(Int,String) tuples will fail:
```
val rawArtistData = sc.textFile(base+"artist_data.txt")
val artistByID = rawArtistData.map { line =>
val (id, name) = line.span(_ != '\t')
(id.toInt, name.trim)
}
```

The parsing does not fail and generates an RDD.

```
artistByID: org.apache.spark.rdd.RDD[(Int, String)] = MappedRDD[14] at map at <c
onsole>:16
```
