### ISSUE TITLE
Chapter 11 data set: 404

### ISSUE THREAD

**Issue by TedMorris54** [sryza/aas#25]
I'm trying to get the zebrafish data set.  Seems the down-scaled sample is no longer in the Thunder distro.

**Comment by srowen** [comment]
Looks like the `v0.4.1` tag got renamed. Try https://github.com/thunder-project/thunder/tree/v0.4.1/python/thunder/utils/data/fish/tif-stack ; I'll update the web site and see if I can post an erratum for the book.

**Comment by TedMorris54** [comment]
Thank you.


Ted Morris
IBM Emerging Technologies Group | jStart® Team
Office    +1 919 486 0181
Mobile    +1 507 250 0602
Email      eamorris@us.ibm.com
