### ISSUE TITLE
Problems build Chapter 6 (and also the root)

### ISSUE THREAD

**Issue by dbl001** [sryza/aas#26]
Hi,
I'm running on Ubuntu 14.04 LTS on an EC2 instance.
ubuntu@ip-10-0-1-186:~/aas$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
ubuntu@ip-10-0-1-186:~/aas$ 

When I tried to run $mvn package in ch06-lsa:
ubuntu@ip-10-0-1-186:~/aas/ch06-lsa$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Wikipedia Latent Semantic Analysis 1.0.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.cloudera.datascience:common:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.057s
[INFO] Finished at: Tue May 26 21:14:19 UTC 2015
[INFO] Final Memory: 11M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ch06-lsa: Could not resolve dependencies for project com.cloudera.datascience:ch06-lsa:jar:1.0.0: Failure to find com.cloudera.datascience:common:jar:1.0.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ubuntu@ip-10-0-1-186:~/aas/ch06-lsa$ 

When I tried to run mvn in the root:

ubuntu@ip-10-0-1-186:~/aas$ mvn install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Advanced Analytics with Spark
[INFO] Advanced Analytics with Spark Common
[INFO] Introduction to Data Analysis with Scala and Spark
[INFO] Recommender Engines with Audioscrobbler data
[INFO] Covtype with Random Decision Forests
[INFO] Anomaly Detection with K-means
[INFO] Wikipedia Latent Semantic Analysis
[INFO] Network Analysis with GraphX
[INFO] Temporal and Geospatial Analysis
[INFO] Value at Risk through Monte Carlo Simulation
[INFO] Genomics Analysis with ADAM
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Advanced Analytics with Spark 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce) @ spark-book-parent ---
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.0.5 is not in the allowed range 3.1.1.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Advanced Analytics with Spark ..................... FAILURE [1.570s]
[INFO] Advanced Analytics with Spark Common .............. SKIPPED
[INFO] Introduction to Data Analysis with Scala and Spark  SKIPPED
[INFO] Recommender Engines with Audioscrobbler data ...... SKIPPED
[INFO] Covtype with Random Decision Forests .............. SKIPPED
[INFO] Anomaly Detection with K-means .................... SKIPPED
[INFO] Wikipedia Latent Semantic Analysis ................ SKIPPED
[INFO] Network Analysis with GraphX ...................... SKIPPED
[INFO] Temporal and Geospatial Analysis .................. SKIPPED
[INFO] Value at Risk through Monte Carlo Simulation ...... SKIPPED
[INFO] Genomics Analysis with ADAM ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.867s
[INFO] Finished at: Tue May 26 21:15:21 UTC 2015
[INFO] Final Memory: 14M/285M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce) on project spark-book-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ubuntu@ip-10-0-1-186:~/aas$ 

Any ideas?

**Comment by dbl001** [comment]
Never mind!

It wanted maven 3.3.3 

ubuntu@ip-10-0-1-186:~/aas/ch06-lsa$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T11:57:37+00:00)
Maven home: /usr/local/apache-maven/apache-maven-3.3.3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-53-generic", arch: "amd64", family: "unix"

**Comment by srowen** [comment]
Yeah, you don't have to `install` if you are building all modules at once, but if you are building just one module, at least the common module would have to have been built previously and `install`ed locally.

And yes the build requires Maven 3.1. That's pretty old now so I figured it wasn't much of an issue. I think you could probably change it to use Maven 3.0 with little issue if necessary.

**Comment by dbl001** [comment]
Curiosly - Maven 3.0.5 is what get’s installed on an Ubuntu EC2 instance.
I tried updating maven with apt-get but it didn’t work.
I had to remove the apt-get version and download the apache-maven version.

Before:

ubuntu@ip-10-0-1-186:~/aas$ mvn -version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-53-generic", arch: "amd64", family: “unix"

After:

ubuntu@ip-10-0-1-186:~/aas/ch06-lsa$ mvn -version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T11:57:37+00:00)
Maven home: /usr/local/apache-maven/apache-maven-3.3.3
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-53-generic", arch: "amd64", family: "unix"

**Comment by srowen** [comment]
OK, fair enough. There's not a strong reason to require 3.1, so I changed it to allow 3.0.5:
https://github.com/sryza/aas/commit/eed30d7214e0e7996068083f2ac6793e6375a768

**Comment by chenaidong** [comment]
Hi Owen,

        When I go through script at chapter 06, I always stuck at the following:

scala> def createNLPPipeline(): StanfordCoreNLP = {
     | val props = new Properties()
     | props.put("annotators", "tokenize, ssplit, pos, lemma")
     | new StanfordCoreNLP(props)
     | }
<console>:28: error: not found: type Properties
       val props = new Properties()

        The build succeeded. Then I copied the whole aas directory to another machine, which is the spark client that can talk to a cluster.  The command to invoke the spark is
spark-shell  --jars /home/achen/aas/ch06-lsa/target/ch06-lsa-1.0.1-jar-with-dependencies.jar  --master  yarn    --executor-cores  12  --executor-memory 24g  --num-executors 10

         May I get help on how to fix the issue? Thanks.

Aidong

**Comment by srowen** [comment]
@chenaidong looks like you did not import `java.util.Properties`. (Better to create a new issue, as it's not related to this one, though I think that's already the explanation.)
