### ISSUE TITLE
Can I run the 'AAS' code from a Zepplin Notebook?

### ISSUE THREAD

**Issue by dbl001** [sryza/aas#28]
Can I run the 'AAS' Code from Zepplin?
If yes, how do I import the chapter's .jar?

Spark Shell:
~/spark/bin/spark-shell --jars target/ch06-lsa-1.0.0.jar

Zeppelin:
./bin/zeppelin-daemon.sh start
Pid dir doesn't exist, create /home/ubuntu/incubator-zeppelin/run
Zeppelin start                                             [  OK  ]

Thanks in advance!

**Comment by srowen** [comment]
Yes, I don't see why not. I don't have any experience with Zeppelin though, and it sounds specific to how you configure that project, so Zeppelin docs may be the better place to check.
