### ISSUE TITLE
Chapter 6: numDocs not defined

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#31]
Forgive me if I'm opening and closing too many issues...

Chapter 6 has the code:

val idfs = docFreqs.map{
	case (term, count) => (term, math.log(numDocs.toDouble / count))
}.toMap

I don't see numDocs defined in any of the code up to this point.  Is this a typo?  Should it be numTerms?

**Comment by srowen** [comment]
You're right, that doesn't work by itself in the text. @sryza I think that the easiest way to bridge this difference with the source is to add before this:
```
val numDocs = docTermFreqs.count()
```
? If so I can make an erratum.

**Comment by jackRogers** [comment]
I've had a few other issues where functions where undefined and I had to import additional libraries which you may also want to add into the examples, unless I've been doing something wrong.  Not sure if this is the proper place to post all of those though

**Comment by srowen** [comment]
The code in the book is an abbreviated form of the source repo, although it's supposed to still work together as given in the listings (if you execute it all, in order). There are likely some gaps though.

**Comment by jackRogers** [comment]
The ch06 lsa source imports do not resolve all of the issues I've encountered in the book examples.  There is also quite a few things being done in the book examples that are not in the source repo.  Not really sure where to turn at this point to get this example working other than continuing to open somewhat trivial issues for this github repo. :(

**Comment by srowen** [comment]
Yes, the book source is not supposed to be exactly like the source repo, though should be broadly similar. Book source is modified to fit better into the text. Importing the source repo code doesn't necessarily help with the source presented in the book. Still the book source is supposed to work by itself. You can file any other issues you find, yes.

**Comment by jackRogers** [comment]
Roger that, will do, thanks for all the help.

**Comment by srowen** [comment]
I'm opening an erratum to track this, since we need some tweak the text in any event.
