### ISSUE TITLE
ch06 - value toMap is not a member of org.apache.spark.rdd.RDD[(String, Double)]

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#32]
When using the book's example code:

val idfs = docFreqs.map{
     |     case (term, count) => (term, math.log(numDocs.toDouble / count))
     | }.toMap

I get back:

<console>:104: error: value toMap is not a member of org.apache.spark.rdd.RDD[(String, Double)]
possible cause: maybe a semicolon is missing before `value toMap'?
       }.toMap
         ^

Currently importing:
import com.cloudera.datascience.common.XmlInputFormat
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.io._
import org.apache.spark.SparkContext._

//lemmatization
import edu.stanford.nlp.pipeline._
import edu.stanford.nlp.ling.CoreAnnotations._

//need properties class
import java.util.Properties

//need array buffer class
import scala.collection.mutable.ArrayBuffer

//need rdd class
import org.apache.spark.rdd.RDD

//need foreach 
import scala.collection.JavaConversions._

//computing the tf-idfs
import scala.collection.mutable.HashMap

**Comment by srowen** [comment]
@sryza in the source repo, `docFreqs` is an `Array`, but as used in the book it's an `RDD`. This will need to be `collectAsMap()` right?

**Comment by srowen** [comment]
Filed as an erratum.
