### ISSUE TITLE
chapter 6: termDocMatrix not defined

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#36]
In chapter 6,

termDocMatrix.cache()

This variable isn't defined earlier in the chapter.  I haven't been able to find a suitable way to do this without changing everything to be more like RunLSA, which creates a differnt set of issues.  

Any assistance appreciated

**Comment by srowen** [comment]
Yeah that should just be the `vecs` variable from above. I'll make an erratum. Just closing this since there won't be a corresponding code change here in the repo.

**Comment by jackRogers** [comment]
ty!  Was digging out portions of code from RunLSA and ParseWikipedia trying to get it to work
