### ISSUE TITLE
I have 2 questions.

### ISSUE THREAD

**Issue by iamdiffuser** [sryza/aas#37]
1:I tried the code in chapt5 Kmens-clousters. In my eclipse for scal, there are some complie error about Vector.
  def distance(a: Vector,b: Vector) = math.sqrt(a.toArray.zip(b.toArray).map(p => p._1 - p._2).map(d => d * d).sum)
there is a error about Vector: type vector takes type parameters.
I don't know what's wrong.

2:Then I tried the code in chapt8. I couldn't get a jar where contain "com.cloudera.datascience.geotime.GeoJsonProtocol._". 

In pom.xml there is a dependency
    <dependency>
      <groupId>com.cloudera.datascience</groupId>
      <artifactId>common</artifactId>
      <version>${project.version}</version>
    </dependency>

where can I fetch this "common" jar. I don't found it in site "http://mvnrepository.com/".

Could someone help me ?
thanks.

**Comment by iamdiffuser** [comment]
question 2, I konw the reason. I put the code in a new package "scala.chapt08", so I need "import scala.chapt08.GeoJsonProtocol._" in RunGeoTime.java

**Comment by srowen** [comment]
For `Vector`, maybe you have the wrong type imported? You need to import the one from Spark MLlib.
For `GeoJsonProtocol`, that class is in the code accompanying the book. It is not published in Maven. You do not need to copy and paste it anywhere. As the book text shows, you build the code locally and then use `--jars target/ch08-geotime-1.0.0.jar` to use it in a Spark shell.

**Comment by malihaddad** [comment]
Hi. trying to run "mvn package" but get this issue:
[WARNING] The POM for com.cloudera.datascience:common:jar:1.0.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.724 s
[INFO] Finished at: 2015-10-30T10:30:19-07:00
[INFO] Final Memory: 13M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ch08-geotime: Could not resolve dependencies for project com.cloudera.datascience:ch08-geotime:jar:1.0.2: Failure to find com.cloudera.datascience:common:jar:1.0.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
Any help is appreciated.

**Comment by srowen** [comment]
@malihaddad please don't hijack another issue, but, I can't reproduce this. You run `mvn package` from the top level.

**Comment by malihaddad** [comment]
Thanks for the reply and sorry about that: first time I post a comment. didn't pay attention on the status of the post (closed) and the new issue button on top!  Thanks again.
