### ISSUE TITLE
Ch10: adamLoad error

### ISSUE THREAD

**Issue by tcfuji** [sryza/aas#40]
Getting the following in the adam-shell:

```scala
scala> import org.bdgenomics.adam.rdd.ADAMContext._
import org.bdgenomics.adam.rdd.ADAMContext._

scala> import org.bdgenomics.formats.avro.AlignmentRecord
import org.bdgenomics.formats.avro.AlignmentRecord

scala> val readsRDD: RDD[AlignmentRecord] = sc.adamLoad("genomics/reads/HG00103")
<console>:20: error: value adamLoad is not a member of org.apache.spark.SparkContext
       val readsRDD: RDD[AlignmentRecord] = sc.adamLoad("genomics/reads/HG00103")
```

**Comment by srowen** [comment]
CC @laserson 

Are you using a later version of ADAM than in the text? It looks like that method may have become `loadParquet`, but only recently:

https://github.com/bigdatagenomics/adam/pull/688/files

**Comment by tcfuji** [comment]
I followed the instructions in the book, which required cloning the repository.
I tried `sc.loadAlignment` and that seemed to work fine.

**Comment by srowen** [comment]
Ah yes, the text will need to direct people to checkout ADAM as of the release that was used in the text, which should be 0.16.0. Can you try this instead?

```
git clone -b adam-parent-0.16.0 https://github.com/bigdatagenomics/adam.git
```

**Comment by srowen** [comment]
I'm pretty certain this is the necessary fix. I'm tracking this as an erratum for the text, since it's the text that's affected rather than this source repo: http://www.oreilly.com/cs/portal/edit/errata/154491
