### ISSUE TITLE
ch09 - Missing classes

### ISSUE THREAD

**Issue by skp33** [sryza/aas#41]
Inside `package com.cloudera.datascience.risk`, I am not able to find out these two classes 
`import com.cloudera.datascience.risk.ComputeFactorWeights._`
`import com.cloudera.datascience.risk.MonteCarloReturns._`

Here is the link https://github.com/sryza/aas/blob/master/ch09-risk/shell.scala#L11-L12 where you are importing these classes.

**Comment by srowen** [comment]
@sryza looks like that bit of shell needs to be updated too -- I don't see those classes either.

**Comment by sryza** [comment]
Ah this file should actually not be in the repo at all
