### ISSUE TITLE
def loadMedline code has incorrect start and end tag keys (MedlineCitation instead of MetlineCitationSet)

### ISSUE THREAD

**Issue by bilalaslamseattle** [sryza/aas#42]
Kept getting XML errors when running the code pasted from here and found the issues at lines 186 and 187 - that should be MedlineCitationSet.

https://github.com/sryza/aas/blob/master/ch07-graph%2Fsrc%2Fmain%2Fscala%2Fcom%2Fcloudera%2Fdatascience%2Fgraph%2FRunGraph.scala#L186

**Comment by srowen** [comment]
No, it intends to parse each `MedlineCitation` element since each one is a citation record. What errors do you get though?

**Comment by bilalaslamseattle** [comment]
It specifically starts to throw the exceptions below (that look like a badly formed XML) when it hits the val topicCounts line below: 

val topics: RDD[String] = medline.flatMap(mesh => mesh) val topicCounts = topics.countByValue()

Errors:

/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:55166,suspend=y,server=n -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/lib/dt.jar:...
com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441) at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) at com.sun.org.apache.xerces.inte

**Comment by srowen** [comment]
Hm, I'm still not sure what to make of that. The error here is just the bit from within the XML parsers where errors are handled. It doesn't say what the cause was. Do you have any more info?

The idea is that `XMLInputFormat` should hand whole `<MedlineCitation>` elements to the map function for parsing.

Is it possible there is some other stray file in the directory with your XML files?

**Comment by srowen** [comment]
We can reopen this if there's a bit more detail.
