### ISSUE TITLE
ch06 - error: value _1 is not a member of scala......

### ISSUE THREAD

**Issue by jackRogers** [sryza/aas#43]
```
<console>:93: error: value _1 is not a member of scala.collection.mutable.HashMap[String,Int]
       val docIds = docTermFreqs.map(_._1).zipWithUniqueId().map(_.swap).collectAsMap()
```

The code in the book doesn't define any variables called docIds and I don't see any comments about it in the code.  Having trouble debugging this as I'm not sure exactly what this line is trying to accomplish.  What does `(_._1)` mean?

It's a bit frustrating that the code in the book doesn't work and I can't manage to get the code on github to work either.  Any help would be much appreciated

**Comment by srowen** [comment]
`_1` and `_2` refer to the first and second elements of a pair or tuple in Scala. `map(_._1)` means "turn pairs into their keys".

The code compiles in the repo so I think it's correct as-is. It does work differently than in the book and I don't think you can mix the two. For example in the book, `docTermFreqs` is not and RDD of pairs, so this line here won't work. However the usage of `docTermFreqs` in the book will.

The near-but-not-total consistency between text and repo can create confusion in a few places; it may just be how it is at this stage. If you stick to one or the other it should be internally consistent.

CC @sryza
