### ISSUE TITLE
ch08 error: not found: type DateTime  

### ISSUE THREAD

**Issue by kdempsey** [sryza/aas#48]
Hi, I have built the mvn package from the root to create all the jar files for the chapters. I copied the jar file for ch08 into the external folder of the spark-1.5.0 install and start with ./bin/spark-shell --jars external/ch08-geotime-1.0.1-jar-with-dependencies.jar --master local[*]
All the imports work ok including import com.github.nscala_time.time.Imports._
I can create new datatime e.g. val test = new DateTime
but when I run 
case class Trip(
  pickupTime: DateTime,
  dropoffTime: DateTime,
  pickupLoc: Point,
  dropoffLoc: Point)
I get the error: error: not found: type DateTime  

Could you please give me a tip as to why it would work for creating a new object but not recognised in the case class?
Many thanks,

**Comment by srowen** [comment]
Yes, `import com.github.nscala_time.time.Imports._` should be what brings you this class, but I also see the same problem. Hm. Instead of that import, try importing `org.joda.time.DateTime` directly. It worked for me. I think we may have to adjust the example to not use this Scala typedef indirection as it is having a strange interaction with the shell, case class and classloaders.

**Comment by kdempsey** [comment]
Thanks for getting back to me so quickly, yes that works.

**Comment by srowen** [comment]
Resolved by https://github.com/sryza/aas/pull/49

**Comment by williamtellme123** [comment]
Neither work for me unfortunately:
import com.github.nscala_time.time.Imports._
import org.joda.time.DateTime

case class Trip(
  pickupTime: DateTime,
  dropoffTime: DateTime,
  pickupLoc: Point,
  dropoffLoc: Point)
error: not found: type DateTime

**Comment by eubnara** [comment]
@williamtellme123 

I fix it as follows:

  ```
case class Trip(
 pickupTime: org.joda.time.DateTime,
 dropoffTime: org.joda.time.DateTime,
 pickupLoc: com.esri.core.geometry.Point,
 dropoffLoc: com.esri.core.geometry.Point)
```

I don't know why I should declare like above.
