### ISSUE TITLE
How do you run these .jar files?

### ISSUE THREAD

**Issue by simsong** [sryza/aas#50]
It's not clear how to run the .jar files from the documentation. For example, ch06-lsa requires the file `stopwords.txt`, but that file is in target/classes/stopwords.txt and in src/main/resources/stopwords.txt. When the jar file is run with this command: `spark-submit --class com.cloudera.datascience.lsa.RunLSA target/ch06-lsa-1.0.2-jar-with-dependencies.jar` an error is generated indicating that the file `stopwords.txt` can't be found.

**Comment by srowen** [comment]
They're not _really_ meant to be run as-is, even though several chapter try to collect all the example code into runnable segments triggered by a main method. Really, they're elaborated, completed versions of the snippets in the book for reference. The intent is mostly that you follow along with the book by typing in the shell in order in each chapter. That is intended to work.

To your question, yes you probably have to copy that file into your root working directory if you're trying to run with `spark-submit`.

**Comment by simsong** [comment]
Thanks for the news, although this is disappointing. I'm planning on using the book in a course, and it would be really useful if students could run the example code....  I'll give it another shot.

(The book doesn't do a very good job explaining the directory structure, or how to run complex scala programs. I need a better reference for maven and the rest of the build environment.)

Thanks for making the resource available, though. And the book really is good, although it could use more detail in places.

**Comment by srowen** [comment]
To be clear, you are definitely intended to run the code as you see it in
the book. I am not sure what problem you are having? It requires no
directories or Maven. Did you read the intro about the Scala shell? All you
need . repo is not required.

**Comment by simsong** [comment]
I understand that the repo is not required and that the entire script can be pasted into the live shell. But I'm also interested in using these scripts as the basis to build a much larger system, so it's important to know how to use Maven, which means using the directory structure that you created.

**Comment by srowen** [comment]
In that case I'd use the source code as source rather than as Maven artifacts, and cut out parts you want and/or modify them to taste. These are not even published as artifacts, though the build is handled by Maven.
