### ISSUE TITLE
ch04-rdf

### ISSUE THREAD

**Issue by hechemeljed** [sryza/aas#58]
Hey guys , 
I am new with Spark, so I was trying to test the RDF and it is not showing all the tests like evaluateCategorical() and evaluateForest(). Any idea about the issue ? 

Cheers,
![start](https://cloud.githubusercontent.com/assets/10809104/12812656/3202f924-cb6e-11e5-9e4e-7e792542215d.jpg)

**Comment by srowen** [comment]
It looks like you killed it while running. Is that why?
Although you can run it this way its not useful. You really want to execute snippets in the shell as you follow along the text.
