### ISSUE TITLE
ch06 compile

### ISSUE THREAD

**Issue by uzink** [sryza/aas#59]
Hi,

I am getting the following error when I try to compile ch06

[ERROR] Failed to execute goal on project ch06-lsa: Could not resolve dependencies for project com.cloudera.datascience:ch06-lsa:jar:1.0.2: Could not find artifact com.cloudera.datascience:common:jar:1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by srowen** [comment]
It means you didn't `install` the artifacts when you built from the top level, and you are also not building from the top level. Do one or the other.
