### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by cclvr** [sryza/aas#60]
hello, when I compile the project by "mvn package", there exist the following errors:
[ERROR] uncaught exception during compilation: java.lang.AssertionError
[ERROR] error: java.lang.AssertionError: assertion failed: org.json.JSONException
...
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (default) on project ch08-geotime: wrap: org.apache.commons.exec.ExecuteException:
 Process exited with an error: 240 (Exit value: 240) -> [Help 1][ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

could you please to help? thank you a lot

**Comment by cclvr** [comment]
oh, the above problem occurs when I compiled the ch08-geotime project

**Comment by srowen** [comment]
I can't reproduce any problem. `mvn clean package` from the top level works, and the Travis builds are green. This looks like some kind of local / internal error, but I don't know what could cause `JSONException`. Try a clean build.

**Comment by cclvr** [comment]
It still  doesn't work for me, strange~~~. Thank you all the same~
