### ISSUE TITLE
why use different iterator in function documentFrequencies from com.cloudera.datascience.lsa.ParseWikipedia ? 

### ISSUE THREAD

**Issue by CanoeFZH** [sryza/aas#62]
```
  def documentFrequencies(docTermFreqs: RDD[HashMap[String, Int]]): HashMap[String, Int] = {
    val zero = new HashMap[String, Int]()
    def merge(dfs: HashMap[String, Int], tfs: HashMap[String, Int])
      : HashMap[String, Int] = {
      tfs.keySet.foreach { term =>
        dfs += term -> (dfs.getOrElse(term, 0) + 1)
      }
      dfs
    }
    def comb(dfs1: HashMap[String, Int], dfs2: HashMap[String, Int])
      : HashMap[String, Int] = {
      for ((term, count) <- dfs2) {
        dfs1 += term -> (dfs1.getOrElse(term, 0) + count)
      }
      dfs1
    }
    docTermFreqs.aggregate(zero)(merge, comb)
  }
```

I wonder why using two different iterator in function ```merge``` and ```comb```.  Could you give some more explanation about this details ?

**Comment by CanoeFZH** [comment]
this part code from com.cloudera.datascience.lsa.ParseWikipedia line 77 to line 94

**Comment by noprom** [comment]
@CanoeFZH ,merge and comb are two different operations on collection, maybe there are performance influence on the operation.
This is just what I guess, :)
Hope the author of this piece of code explain the details.

**Comment by CanoeFZH** [comment]
@noprom Yes, I guess that performance may be the consideration. Just want to know more details :)

**Comment by noprom** [comment]
@CanoeFZH ,I see from your profile that you are now in BJ. Are you in a startup now?
Recently, I am learning spark, could you please leave your QQ or Wechat so that we can get further communication with each other?

**Comment by CanoeFZH** [comment]
@noprom I have sent my Wechat ID to your mail.

**Comment by CanoeFZH** [comment]
@noprom  May be just because the ```comb``` function needs use value

**Comment by srowen** [comment]
@sryza I don't think that method is actually used right? it's there for illustration.

In the first case it's ignoring the counts of the words in the doc and simply merging a +1 for each term encountered in the document. Really, the fact that the inputs are maps is irrelevant; the set of keys is all that matters. In the second function the counts from two maps are being merged. They're different because they do different things.

**Comment by sryza** [comment]
@srowen that's right that the method is just for illustration.
