### ISSUE TITLE
ch10 - What module should be added in order to run sc.adamBEDFeatureLoad?

### ISSUE THREAD

**Issue by huboqiang** [sryza/aas#63]
In [https://github.com/sryza/aas/blob/master/ch10-genomics/README.md](https://github.com/sryza/aas/blob/master/ch10-genomics/README.md), line 80, "In a Spark shell, we then convert the PhyloP data from text to Parquet, to
improve performance:"

However, it was not claimed what module should be imported and it seemed no module named "adamBEDFeatureLoad" in the current version of adam.

So I really need your help. Thanks.

**Comment by srowen** [comment]
It's not in the current version of ADAM; as far as I can tell, 0.15.0 was the last version where it existed, and that's the version used by the book. 

(Actually, oops, we declare 0.16.0 in the POM file. @laserson given that, do you think we need to fix the text / README to not refer to this method? is there an easy replacement?)

**Comment by hubqoaing** [comment]
Thanks for your reply. Em, do you have any suggestion for bed => parquet converting using the command in the current version of adam? I tried 

```scala
import org.bdgenomics.adam.rdd.ADAMContext

val ac = new ADAMContext(sc)
val adamBed = ac.loadBED("hdfs://user/hadoop/genomics/phylop_text")
```
 to load files in the dictionary phylop_text, but I do not know how to save the result to parquet format.
```adamBed.adamSave("hdfs://user/hadoop/genomics/phylop_text")``` failed because adamSave were not found.

Thank you.

**Comment by laserson** [comment]
@srowen Yes, an update is sorely needed to this code.

@huboqiang Apologies for the delay.  `loadBED` should successfully load the BED file into `Feature` objects which are part of the Avro model, which should be compatible with the Parquet saving functions.  Did you try `adamParquetSave` on your RDD?

**Comment by srowen** [comment]
Closing this not because it's already fixed but because we know this whole thing will be overhauled for 2nd edition anyway.
