### ISSUE TITLE
Execution time of example in ch04

### ISSUE THREAD

**Issue by macdi** [sryza/aas#65]
Hello,

I tried to experiment the example from chapter 04.
I started the scala script using this command: 
"./bin/spark-submit --class com.cloudera.datascience.rdf.RunRDF ../aas/ch04-rdf/target/ch04-rdf-1.0.2.jar"

After more 30 min of running..., I didn't see any progress. As we can see in the logs below.
My machine configuration is a Linux Ubuntu 14.04 64bits running on a laptop with Intel Core i7-3720QM CPU @ 2.60GHz and 8GB of RAM.
I setup a hadoop cluster as a single node in a pseudo-distributed mode.

Could someone tell me if my configuration is suited to run such a workload?
And for how long should I let the simulation running on my specified configuration?
Is there any missing parameters in my command line that might be used to improve the simulation?
Does someone was able to experiment the same example on a configuration similar to mine?

Thank you very much for your help.
Best regards,

16/03/10 14:50:25 INFO spark.SparkContext: Running Spark version 1.6.0
16/03/10 14:50:25 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/03/10 14:50:26 WARN util.Utils: Your hostname, mahdi-W530 resolves to a loopback address: 127.0.1.1; using 192.168.1.12 instead (on interface wlan0)
16/03/10 14:50:26 WARN util.Utils: Set SPARK_LOCAL_IP if you need to bind to another address
16/03/10 14:50:26 INFO spark.SecurityManager: Changing view acls to: mahdi
16/03/10 14:50:26 INFO spark.SecurityManager: Changing modify acls to: mahdi
16/03/10 14:50:26 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(mahdi); users with modify permissions: Set(mahdi)
16/03/10 14:50:26 INFO util.Utils: Successfully started service 'sparkDriver' on port 40804.
16/03/10 14:50:26 INFO slf4j.Slf4jLogger: Slf4jLogger started
16/03/10 14:50:26 INFO Remoting: Starting remoting
16/03/10 14:50:26 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.1.12:57231]
16/03/10 14:50:26 INFO util.Utils: Successfully started service 'sparkDriverActorSystem' on port 57231.
16/03/10 14:50:26 INFO spark.SparkEnv: Registering MapOutputTracker
16/03/10 14:50:26 INFO spark.SparkEnv: Registering BlockManagerMaster
16/03/10 14:50:26 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-1c210802-919a-4b15-9495-515de1b321e7
16/03/10 14:50:26 INFO storage.MemoryStore: MemoryStore started with capacity 511.1 MB
16/03/10 14:50:26 INFO spark.SparkEnv: Registering OutputCommitCoordinator
16/03/10 14:50:26 INFO server.Server: jetty-8.y.z-SNAPSHOT
16/03/10 14:50:26 INFO server.AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
16/03/10 14:50:26 INFO util.Utils: Successfully started service 'SparkUI' on port 4040.
16/03/10 14:50:26 INFO ui.SparkUI: Started SparkUI at http://192.168.1.12:4040
16/03/10 14:50:26 INFO spark.HttpFileServer: HTTP File server directory is /tmp/spark-d405be22-1b86-48c1-a21f-6a1093902e7e/httpd-d64d4079-4e94-4dc0-b458-4cefb10d89cd
16/03/10 14:50:26 INFO spark.HttpServer: Starting HTTP Server
16/03/10 14:50:26 INFO server.Server: jetty-8.y.z-SNAPSHOT
16/03/10 14:50:26 INFO server.AbstractConnector: Started SocketConnector@0.0.0.0:44378
16/03/10 14:50:26 INFO util.Utils: Successfully started service 'HTTP file server' on port 44378.
16/03/10 14:50:26 INFO spark.SparkContext: Added JAR file:/home/mahdi/BigData/spark-1.6.0-bin-hadoop2.6/../aas/ch04-rdf/target/ch04-rdf-1.0.2.jar at http://192.168.1.12:44378/jars/ch04-rdf-1.0.2.jar with timestamp 1457617826975
16/03/10 14:50:27 INFO executor.Executor: Starting executor ID driver on host localhost
16/03/10 14:50:27 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 53804.
16/03/10 14:50:27 INFO netty.NettyBlockTransferService: Server created on 53804
16/03/10 14:50:27 INFO storage.BlockManagerMaster: Trying to register BlockManager
16/03/10 14:50:27 INFO storage.BlockManagerMasterEndpoint: Registering block manager localhost:53804 with 511.1 MB RAM, BlockManagerId(driver, localhost, 53804)
16/03/10 14:50:27 INFO storage.BlockManagerMaster: Registered BlockManager
16/03/10 14:50:27 INFO storage.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 127.5 KB, free 127.5 KB)
16/03/10 14:50:27 INFO storage.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 14.0 KB, free 141.5 KB)
16/03/10 14:50:27 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:53804 (size: 14.0 KB, free: 511.1 MB)
16/03/10 14:50:27 INFO spark.SparkContext: Created broadcast 0 from textFile at RunRDF.scala:21
data loaded, start training...
16/03/10 14:50:27 INFO mapred.FileInputFormat: Total input paths to process : 1
16/03/10 14:50:28 INFO spark.SparkContext: Starting job: take at DecisionTreeMetadata.scala:110
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Got job 0 (take at DecisionTreeMetadata.scala:110) with 1 output partitions
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Final stage: ResultStage 0 (take at DecisionTreeMetadata.scala:110)
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[7] at map at DecisionTreeMetadata.scala:110), which has no missing parents
16/03/10 14:50:28 INFO storage.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 4.1 KB, free 145.6 KB)
16/03/10 14:50:28 INFO storage.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.3 KB, free 147.9 KB)
16/03/10 14:50:28 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on localhost:53804 (size: 2.3 KB, free: 511.1 MB)
16/03/10 14:50:28 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1006
16/03/10 14:50:28 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[7] at map at DecisionTreeMetadata.scala:110)
16/03/10 14:50:28 INFO scheduler.TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
16/03/10 14:50:28 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, partition 0,ANY, 2203 bytes)
16/03/10 14:50:28 INFO executor.Executor: Running task 0.0 in stage 0.0 (TID 0)
16/03/10 14:50:28 INFO executor.Executor: Fetching http://192.168.1.12:44378/jars/ch04-rdf-1.0.2.jar with timestamp 1457617826975
16/03/10 14:50:28 INFO util.Utils: Fetching http://192.168.1.12:44378/jars/ch04-rdf-1.0.2.jar to /tmp/spark-d405be22-1b86-48c1-a21f-6a1093902e7e/userFiles-7c0ff571-14f4-4f03-86d2-02d2c9c51fa9/fetchFileTemp7982476539242282119.tmp
16/03/10 14:50:28 INFO executor.Executor: Adding file:/tmp/spark-d405be22-1b86-48c1-a21f-6a1093902e7e/userFiles-7c0ff571-14f4-4f03-86d2-02d2c9c51fa9/ch04-rdf-1.0.2.jar to class loader
16/03/10 14:50:28 INFO spark.CacheManager: Partition rdd_3_0 not found, computing it
16/03/10 14:50:28 INFO rdd.HadoopRDD: Input split: hdfs://localhost:9001/user/ds/covtype.data:0+37584658
16/03/10 14:50:28 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
16/03/10 14:50:28 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
16/03/10 14:50:28 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
16/03/10 14:50:28 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
16/03/10 14:50:28 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
16/03/10 14:50:30 INFO storage.MemoryStore: Block rdd_3_0 stored as values in memory (estimated size 45.6 MB, free 45.7 MB)
16/03/10 14:50:30 INFO storage.BlockManagerInfo: Added rdd_3_0 in memory on localhost:53804 (size: 45.6 MB, free: 465.5 MB)
16/03/10 14:50:30 INFO executor.Executor: Finished task 0.0 in stage 0.0 (TID 0). 2611 bytes result sent to driver
16/03/10 14:50:30 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 2518 ms on localhost (1/1)
16/03/10 14:50:30 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/03/10 14:50:30 INFO scheduler.DAGScheduler: ResultStage 0 (take at DecisionTreeMetadata.scala:110) finished in 2.529 s
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Job 0 finished: take at DecisionTreeMetadata.scala:110, took 2.583556 s
16/03/10 14:50:30 INFO spark.SparkContext: Starting job: count at DecisionTreeMetadata.scala:114
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Got job 1 (count at DecisionTreeMetadata.scala:114) with 2 output partitions
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Final stage: ResultStage 1 (count at DecisionTreeMetadata.scala:114)
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Parents of final stage: List()
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Missing parents: List()
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[6] at retag at RandomForest.scala:135), which has no missing parents
16/03/10 14:50:30 INFO storage.MemoryStore: Block broadcast_2 stored as values in memory (estimated size 3.7 KB, free 45.7 MB)
16/03/10 14:50:30 INFO storage.MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 2.1 KB, free 45.7 MB)
16/03/10 14:50:30 INFO storage.BlockManagerInfo: Added broadcast_2_piece0 in memory on localhost:53804 (size: 2.1 KB, free: 465.5 MB)
16/03/10 14:50:30 INFO spark.SparkContext: Created broadcast 2 from broadcast at DAGScheduler.scala:1006
16/03/10 14:50:30 INFO scheduler.DAGScheduler: Submitting 2 missing tasks from ResultStage 1 (MapPartitionsRDD[6] at retag at RandomForest.scala:135)
16/03/10 14:50:30 INFO scheduler.TaskSchedulerImpl: Adding task set 1.0 with 2 tasks
16/03/10 14:50:30 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, localhost, partition 0,PROCESS_LOCAL, 2203 bytes)
16/03/10 14:50:30 INFO executor.Executor: Running task 0.0 in stage 1.0 (TID 1)
16/03/10 14:50:30 INFO storage.BlockManager: Found block rdd_3_0 locally
16/03/10 14:50:30 INFO executor.Executor: Finished task 0.0 in stage 1.0 (TID 1). 2082 bytes result sent to driver
16/03/10 14:50:30 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 18 ms on localhost (1/2)
16/03/10 15:20:27 INFO storage.BlockManagerInfo: Removed broadcast_1_piece0 on localhost:53804 in memory (size: 2.3 KB, free: 465.5 MB)
16/03/10 15:20:27 INFO spark.ContextCleaner: Cleaned accumulator 1

**Comment by srowen** [comment]
It's not a tiny data set, so yeah I think you would find it could take a while. A modern laptop should be OK if you give it enough memory. It may be slow if you're hitting GC pressure. Really the logs aren't as useful info from the UI at port 4040 by default. That'll show you much more about progress
