### ISSUE TITLE
Ch 06 Package / Install Error:  too many files with unapproved licenses

### ISSUE THREAD

**Issue by immersinn** [sryza/aas#67]
From Package / Install at top level, received this error:

[INFO] Reactor Summary:
[INFO] 
[INFO] Advanced Analytics with Spark ..................... SUCCESS [8.178s]
[INFO] Advanced Analytics with Spark Common .............. SUCCESS [1.363s]
[INFO] Introduction to Data Analysis with Scala and Spark  SUCCESS [0.355s]
[INFO] Recommender Engines with Audioscrobbler data ...... SUCCESS [0.294s]
[INFO] Covtype with Random Decision Forests .............. SUCCESS [0.560s]
[INFO] Anomaly Detection with K-means .................... SUCCESS [0.308s]
[INFO] Wikipedia Latent Semantic Analysis ................ FAILURE [5.351s]
[INFO] Network Analysis with GraphX ...................... SKIPPED
[INFO] Temporal and Geospatial Analysis .................. SKIPPED
[INFO] Value at Risk through Monte Carlo Simulation ...... SKIPPED
[INFO] Genomics Analysis with ADAM ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.547s
[INFO] Finished at: Sun Mar 20 19:17:06 MDT 2016
[INFO] Final Memory: 87M/845M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.11:check (default) on project ch06-lsa: Too many files with unapproved license: 3 See RAT report in: /home/trii/gits/aas/ch06-lsa/target/rat.txt -> [Help 1]

Digging into the RAT report, saw this:

3 Unknown Licenses

*******************************

Unapproved licenses:

  derby.log
  metastore_db/db.lck
  metastore_db/service.properties

*******************************

can workaround with, "mvn -Drat.ignoreErrors=true install"

Just thought I'd make you aware in case others ran into the same issue

**Comment by srowen** [comment]
Hm, nothing I'm aware of uses derby, but maybe some third party library does. Although it's fine to `.gitignore` them, you didn't do anything else here? like this isn't sharing a dir with another project or something?

**Comment by immersinn** [comment]
nope, there is only a single project in the directory.  just did a git
clone then ran the maven commands to package and install.

**Comment by srowen** [comment]
Sure do you want to make a pull request with a `.gitignore` entry for these? I can do it too

**Comment by immersinn** [comment]
So I was running into some other issues and decided to wipe my local copy
of the repository and start over.  Everything ran smoothly when I did that,
so something weird must have happened the first go round.  I suppose I
should have fallen back on the "reboot" strategy first...

**Comment by srowen** [comment]
Yeah I hadn't seen that either... it might come up somehow if you run spark-shell from this dir but I'm not sure. We can revisit if it comes up deterministically.

**Comment by dbl001** [comment]
I just ran into this error on OS X 10.11.5
It doesn't happen on Ubuntu 14.04 LTS.

This command resolved the error:
$ mvn -Drat.ignoreErrors=true install
