### ISSUE TITLE
Error: type mismatch: val plainText = rawXmls.flatMap(wikiXmlToPlainText)

### ISSUE THREAD

**Issue by dbl001** [sryza/aas#71]
Any ideas on this error in Chapter 6?

<console>:199: error: type mismatch;
 found   : String => Iterable[(String, String)]
 required: ((org.apache.hadoop.io.LongWritable, org.apache.hadoop.io.Text)) => TraversableOnce[?]
         val plainText = rawXmls.flatMap(wikiXmlToPlainText)

![screen shot 2016-07-23 at 8 58 12 pm](https://cloud.githubusercontent.com/assets/3105499/17081731/703daeb6-5118-11e6-8fa0-03b0f972bddc.png)

**Comment by srowen** [comment]
What are we looking at here? if you've modified the code, it's probably those changes that are causing the problem, because all of the code here compiles as is. It's not that useful to paste a picture of the code; paste the relevant section as formatted text here.

**Comment by dbl001** [comment]
Mea Culpa.  I broke the code into sections in Zeppelin, which appears to have caused the error(s).
