### ISSUE TITLE
chapter 6 maven project fails to build due to missing dep

### ISSUE THREAD

**Issue by Gaasmann** [sryza/aas#73]
Hello,

I fetched the last commit of the branch master and the maven project for chapter 6 (lsa) doesn't build because of dependency issue:
[ERROR] Failed to execute goal on project ch06-lsa: Could not resolve dependencies for project com.cloudera.datascience:ch06-lsa:jar:2.0.0: Could not find artifact com.cloudera.datascience:common:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
Can you help me?

Thanks

**Comment by srowen** [comment]
You need to build the whole project from the top level, in which case Maven understands the existence of all the modules (some of which depend on each other). Or, you can `mvn install` the modules to make them available locally and then build any module individually. I recommend the former. If you see any documentation that isn't consistent with this let me know.

**Comment by Gaasmann** [comment]
Hello,
I followed the instruction on the printed edition page 103 asking to go to "lsa" directory (which I suppose is "ch06-lsa" now) and run the mvn package command.
That said, I tried to build from top level as you'd said and it worked like a charm.
Thanks a lot,
Nicolas

**Comment by srowen** [comment]
@Gaasmann oops, good catch, I'll fix that for the 2nd edition.
