### ISSUE TITLE
CH 6 wiki dataset link from README results in 404

### ISSUE THREAD

**Issue by jhlch** [sryza/aas#79]

**Comment by srowen** [comment]
Yeah, they scroll off old dumps after a year or so. I'll update it on the site even for the 1st edition because I"m sure people will figure out the file name difference. I'll update the text too though Sandy will surely be rewriting this anyway.

**Comment by srowen** [comment]
https://github.com/sryza/aas/commit/88aa80b7e1d11348a973329cd56f0811d71eb0ca
