### ISSUE TITLE
Can't download donation.zip data set

### ISSUE THREAD

**Issue by slachterman** [sryza/aas#87]
The URL for the donation.zip data set appears to be broken: https://archive.ics.uci.edu/ml/machine-learning-databases/00210/

**Comment by srowen** [comment]
Hm, the whole https://archive.ics.uci.edu/ site seems to be offline. I hope that's temporary -- it's a pretty popular source! Let's wait to see if it comes back, as I hope it will.

In the meantime, I think it's defensible to temporarily offer a link to download this data set separately. I had previously downloaded a copy. Try this:

https://drive.google.com/open?id=0B_hfrkaWlLi4QWxSMlNvdTNpY3c

**Comment by srowen** [comment]
The site is back now anyway.
