### ISSUE TITLE
maven project error

### ISSUE THREAD

**Issue by ysunmi0427** [sryza/aas#94]
In capter 6, where is the exact location I have to run maven package?

I got following error message when I run maven package in **ch06-lsa**.

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.cloudera.datascience:ch06-lsa:2.0.0: Failure to find com.cloudera.datascience:spark-book-parent:pom:2.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 9, column 11
 @ 

And I got following error message when I run maven package in **lsa under data science repo**.

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.063 s
[INFO] Finished at: 2016-12-30T16:37:20+09:00
[INFO] Final Memory: 7M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/coupang/IdeaProjects/chapter6/ch06-lsa/src/main/scala/com/cloudera/datascience/lsa). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Thank you.

**Comment by srowen** [comment]
It's in the README -- you run from the project root.
